### ISSUE TITLE
Support screen rotation on Android

### ISSUE THREAD

**Issue by marcprux** [skiptools/skip-ui#20]
Running the Showcase sample in an emulator with "Auto-rotate" set to "On" and then rotating the screen causes the app to crash. 

The following exception shows up in logcat:

```exception
FATAL EXCEPTION: main
    Process: skip.showcase.App, PID: 16568
    java.lang.NullPointerException: Attempt to invoke virtual method 'void skip.ui.Navigator.didCompose$SkipUI_debug(androidx.navigation.NavHostController, skip.lib.Dictionary, androidx.compose.ui.platform.SoftwareKeyboardController, androidx.compose.runtime.Composer, int)' on a null object reference
    at skip.ui.NavigationStack.ComposeContent(Navigation.kt:94)
    at skip.ui.View$DefaultImpls.Compose(View.kt:858)
    at skip.ui.NavigationStack.Compose(Navigation.kt:71)
    at skip.ui.View$searchable$1$2.invoke(View.kt:238)
    at skip.ui.View$searchable$1$2.invoke(View.kt:234)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at skip.ui.EnvironmentValues$setValues$1.invoke(Environment.kt:72)
    at skip.ui.EnvironmentValues$setValues$1.invoke(Environment.kt:72)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at skip.ui.EnvironmentValues.setValues$SkipUI_debug(Environment.kt:72)
    at skip.ui.View$searchable$1.invoke(View.kt:234)
    at skip.ui.View$searchable$1.invoke(View.kt:228)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at skip.ui.ComposeModifierView.ComposeContent(ComposeModifierView.kt:60)
    at skip.ui.View$DefaultImpls.Compose(View.kt:858)
    at skip.ui.ComposeModifierView.Compose(ComposeModifierView.kt:26)
    at showcase.module.ContentView$body$1.invoke(ContentView.kt:315)
    at showcase.module.ContentView$body$1.invoke(ContentView.kt:159)
    at skip.ui.ComposeView.ComposeContent(ComposeView.kt:39)
    at skip.ui.ComposeView.Compose(ComposeView.kt:32)
    at showcase.module.ContentView.ComposeContent(ContentView.kt:326)
    at skip.ui.View$DefaultImpls.Compose(View.kt:858)
    at showcase.module.ContentView.Compose(ContentView.kt:147)
    at skip.ui.View$task$1.invoke(View.kt:1438)
    at skip.ui.View$task$1.invoke(View.kt:1435)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at skip.ui.ComposeModifierView.ComposeContent(ComposeModifierView.kt:60)
    at skip.ui.View$DefaultImpls.Compose(View.kt:858)
    at skip.ui.ComposeModifierView.Compose(ComposeModifierView.kt:26)
    at showcase.module.RootView$body$1.invoke(ShowcaseApp.kt:32)
    at showcase.module.RootView$body$1.invoke(ShowcaseApp.kt:27)
    at skip.ui.ComposeView.ComposeContent(ComposeView.kt:39)
    at skip.ui.View$DefaultImpls.ComposeContent(View.kt:865)
    at showcase.module.RootView.ComposeContent(ShowcaseApp.kt:22)
    at skip.ui.View$DefaultImpls.Compose(View.kt:858)
    at showcase.module.RootView.Compose(ShowcaseApp.kt:22)
    at skip.ui.View$DefaultImpls.Compose(View.kt:841)
    at showcase.module.RootView.Compose(ShowcaseApp.kt:22)
    at showcase.module.ComposableSingletons$MainKt$lambda-3$1.invoke(Main.kt:134)
    at showcase.module.ComposableSingletons$MainKt$lambda-3$1.invoke(Main.kt:134)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:360)
    at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
    at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:73)
    at showcase.module.MainKt.MaterialThemedRootView(Main.kt:134)
    at showcase.module.ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:62)
    at showcase.module.ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:61)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
    at showcase.module.ComposableSingletons$MainKt$lambda-2$1.invoke(Main.kt:61)
    at showcase.module.ComposableSingletons$MainKt$lambda-2$1.invoke(Main.kt:59)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
    at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
    at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:195)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:158)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:157)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:157)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:142)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
    at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
    at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3340)
    at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3273)
    at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:588)
    at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1013)
    at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
    at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1191)
    at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:133)
    at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:183)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
    at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1266)
    at android.view.View.dispatchAttachedToWindow(View.java:21290)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2820)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
    at android.view.Choreographer.doCallbacks(Choreographer.java:899)
    at android.view.Choreographer.doFrame(Choreographer.java:832)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by marcprux** [comment]
Fixed in 52766e7. Along with the addition of `android:configChanges="orientation|screenSize|screenLayout"` to the `AndroidManifest.xml` `<activity>` element, this gets rotation working in the Showcase app.

<img width="240" alt="Screenshot 2023-11-28 at 19 28 11" src="https://github.com/skiptools/skip-ui/assets/659086/3e5fa8e1-5b22-485b-94c1-1142aed75f61">
<img width="512" alt="Screenshot 2023-11-28 at 19 28 31" src="https://github.com/skiptools/skip-ui/assets/659086/8a75e9bb-3021-486e-ab7e-1941d1eff9b3">
